name: Format Fix

on:
  workflow_dispatch: # 手动触发

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # 针对当前分支

      - name: Run Prettier
        run: |
          npx prettier --write imported.json
          # 如果想修复所有文件，可以用：npx prettier --write .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format imported.json via Prettier"
          branch: ${{ github.head_ref }}
